# Generated by Django 4.0.4 on 2024-01-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='location_name',
            new_name='location',
        ),
    ]
