# Generated by Django 4.0.4 on 2024-01-24 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.unit'),
        ),
        migrations.AlterField(
            model_name='on_request',
            name='unit',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.unit'),
        ),
    ]
