# Generated by Django 4.0.4 on 2024-01-27 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.unit'),
        ),
        migrations.AlterField(
            model_name='on_request',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.status'),
        ),
        migrations.AlterField(
            model_name='on_request',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.unit'),
        ),
        migrations.AlterField(
            model_name='purchase_reference',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.unit'),
        ),
    ]
