# Generated by Django 4.0.4 on 2024-01-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_location_alter_inventory_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='lab stuff', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(default='thing(s)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(default='lab', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(default='in the void', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.CharField(default='unit(s)', max_length=10, unique=True),
        ),
    ]
