# Generated by Django 4.0.4 on 2024-01-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_unit_alter_on_request_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='id',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='id',
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(default='lab', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.CharField(default='unit(s)', max_length=10, primary_key=True, serialize=False),
        ),
    ]
