# Generated by Django 4.0.4 on 2024-01-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_category_category_alter_item_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lab',
            field=models.CharField(default='lab', max_length=25),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='amount',
            field=models.PositiveSmallIntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(default='lab', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_category',
            field=models.CharField(default='count', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('lab', 'location')},
        ),
    ]
