# Generated by Django 4.0.4 on 2024-02-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
