# Generated by Django 4.0.4 on 2024-04-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(default='in the void', max_length=25, unique=True),
        ),
    ]
